image: "python:{{ cookiecutter.python_version }}"

stages:
  - .pre
  - test
  - linting
  - publish

before_script:
  - pip install poetry
  - poetry install

test:
  stage: test
  script:
    - poetry run pytest

pre-commit:
  stage: linting
  script:
    - poetry run pre-commit run --all-files
