[tool.poetry]
name = "{{ package_name }}"
version = "{{ version }}"
description = "{{ project_short_description }}"
authors = [
  "{{ author_name }} <{{ author_email }}>"
]
license = "{{ license }}"
readme = "README.md"
packages = [{include = "{{ package_name }}", from = "src"}]

[tool.poetry.dependencies]
python = "^{{ python_version }}"
{% if package_type == "cli" -%}
click = "^8.1.7"
{%- endif %}

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
flake8 = "^6.1.0"
flake8-builtins = "^2.1.0"
pep8-naming = "^0.13.3"
{% if testing_framework == "pytest" -%}
pytest-mock = "^3.11.1"
flake8-pytest-style = "^1.7.2"
{%- endif %}
{% if use_flake8_strict_plugins -%}
flake8-print = "^5.0.0"
flake8-return = "^1.2.0"
flake8-eradicate = "^1.5.0"
flake8-bugbear = "^23.9.16"
flake8-bandit = "^4.1.1"
{%- endif %}
black = "^22.1.0"
isort = "^5.12.0"
pre-commit = "^3.4.0"
pydocstyle = "^6.3.0"
bump2version = "^1.0.1"
detect-secrets = "^1.4.0"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.core.masonry.api"

{% if package_type == "cli" -%}
[tool.poetry.scripts]
{{ package_name }} = "{{ package_name }}.cli:cli"
{%- endif %}

[tool.black]
line-length = {{ max_line_length }}

[tool.isort]
profile = "black"

[tool.pydocstyle]
add_ignore = "D100,D103,D104"
convention = "google"

[tool.pytest.ini_options]
pythonpath = "src"
