[tool.poetry]
name = "{{ package_name }}"
version = "{{ version }}"
description = "{{ project_short_description }}"
authors = ["{{ author_name }} <{{ author_email }}>"]
license = "{{ license }}"
readme = "README.md"

[tool.poetry.dependencies]
python = "^{{ python_version }}"
{% if package_type == "cli" -%}
click = "8.1.6"
{%- endif %}

[tool.poetry.group.dev.dependencies]
pytest = "6.2.5"
flake8 = "^5.0.0"
flake8-builtins = "^2.1.0"
pep8-naming = "^0.13.3"
{% if testing_framework == "pytest" -%}
pytest-mock = "^3.7.0"
flake8-pytest-style = "^1.7.2"
{%- endif %}
{% if use_flake8_strict_plugins -%}
flake8-print = "^5.0.0"
flake8-return = "^1.2.0"
flake8-eradicate = "^1.4.0"
flake8-bugbear = "^23.2.13"
flake8-bandit = "^4.1.1"
{%- endif %}
black = "^22.1.0"
isort = "^5.10.1"
pre-commit = "^2.17.0"
bump2version = "^1.0.1"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.core.masonry.api"

{% if package_type == "cli" -%}
[tool.poetry.scripts]
{{ package_name }} = "{{ package_name }}.cli:cli"
{%- endif %}

[tool.black]
line-length = {{ max_line_length }}

[tool.isort]
profile = "black"

[tool.pydocstyle]
add_ignore = "D100,D103,D104"
convention = "google"
