_commit: 0.4.0
_src_path: git@gitlab.flowtale.ai:flowtale/internal/cookiecutter-python.git
author_email: sg@flowtale.ai
author_name: Simone Gaiarin
git_hosting: gitlab
ide: vscode
license: MIT license
max_line_length: 88
package_name: copierpythontemplate
package_type: library
project_name: Copier python template
project_short_description: Opinionated copier template for python projects
python_version: '3.10'
testing_framework: pytest
use_flake8_strict_plugins: false
version: 0.3.0
