image: "python:3.10"

stages:
  - .pre
  - test
  - linting

before_script:
  - apt-get update && apt-get install -y make
  - pip install poetry
  - make setup-strict

test:
  stage: test
  script:
    - poetry run tox

pre-commit:
  stage: linting
  script:
    - poetry run pre-commit run --all-files
