image: "python:3.10"

stages:
  - .pre
  - test
  - linting

before_script:
  - pip install poetry
  - poetry install

test:
  stage: test
  script:
    - tox

pre-commit:
  stage: linting
  script:
    - poetry run pre-commit run --all-files
