[tool.poetry]
name = "cookiecutter-python"
version = "0.3.0"
description = "Opinionated copier template for python projects"
authors = ["Simone Gaiarin <simone.gaiarin@trovaprezzi.it>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
flake8 = "^6.0.0"
black = "^22.12.0"
isort = "^5.11.2"
pre-commit = "^2.20.0"
pydocstyle = "^6.3.0"
bump2version = "^1.0.1"
copier = "^8.1.0"
pytest-copier = "^0.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests",
]
markers = [
    "slow: slow tests",
]

[tool.isort]
profile = "black"

[tool.pydocstyle]
add_ignore = "D100,D103,D104"
convention = "google"
