- name: Installing pipx
  apt:
    name: "{{ "{{ packages }}" }}"
    update_cache: true
    cache_valid_time: 604800
  vars:
    packages:
      - python3-venv
      - pipx
  tags: pipx

- name: Ensure directories for pipx to work are ok
  command: "pipx ensurepath"
  become: true
  become_user: "{{ "{{ app_user }}" }}"
  tags: pipx

- name: Set group python package registry of internal gitlab
  command: "pip config set global.index-url https://{{ cookiecutter.gitlab_hostname }}/api/v4/groups/{{ cookiecutter.gitlab_group_slug }}/-/packages/pypi/simple/"
  become: true
  become_user: "{{ "{{ app_user }}" }}"
  tags: pipx
